vich_uploader:
    db_driver: orm
    storage:   flysystem
    mappings:
        student_resume:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         https://s3-%amazon_s3.region%.amazonaws.com/%amazon_s3.bucket%/%file_upload.resume_prefix%
            upload_destination: resume_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        student_avatar:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         https://s3-%amazon_s3.region%.amazonaws.com/%amazon_s3.bucket%/%file_upload.avatar_prefix%
            upload_destination: avatar_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        student_gs1_cert:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         https://s3-%amazon_s3.region%.amazonaws.com/%amazon_s3.bucket%/%file_upload.gs1_cert_prefix%
            upload_destination: gs1_cert_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        student_cert:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         https://s3-%amazon_s3.region%.amazonaws.com/%amazon_s3.bucket%/%file_upload.cert_prefix%
            upload_destination: cert_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

oneup_flysystem:
    adapters:
        s3.resume:
            awss3v3:
                client: amazon_s3.client
                bucket: %amazon_s3.bucket%
                prefix: %file_upload.resume_prefix%
        s3.avatar:
            awss3v3:
                client: amazon_s3.client
                bucket: %amazon_s3.bucket%
                prefix: %file_upload.avatar_prefix%
        s3.gs1_cert:
            awss3v3:
                client: amazon_s3.client
                bucket: %amazon_s3.bucket%
                prefix: %file_upload.gs1_cert_prefix%
        s3.cert:
            awss3v3:
                client: amazon_s3.client
                bucket: %amazon_s3.bucket%
                prefix: %file_upload.cert_prefix%
    filesystems:
        resume_fs:
            adapter:    s3.resume
            mount:      resume_fs
        avatar_fs:
            adapter:    s3.avatar
            mount:      avatar_fs
        gs1_cert_fs:
            adapter:    s3.gs1_cert
            mount:      gs1_cert_fs
        cert_fs:
            adapter:    s3.cert
            mount:      cert_fs