---
- name: create out directory
  sudo: yes
  file: path={{item}} state=directory owner=www-data group={{project_user}} mode=0775
  with_items: out_dirs
  when: not vagrant_env

- name: create out dir
  sudo: yes
  sudo_user: "{{project_user}}"
  file: path={{item}} state=directory
  with_items: out_dirs
  when: vagrant_env
