parameters:
#    app.admin.example.class: App\AdminBundle\Example

services:
    sonata.admin.user:
        class: App\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Users" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - ~
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]

    sonata.admin.student_access_code:
            class: App\AdminBundle\Admin\StudentAccessCodeAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, label: "Student Access Code" }
            arguments:
                - ~
                - App\ResumeBundle\Entity\StudentAccessCode
                - ~

    sonata.admin.institution:
        class: App\AdminBundle\Admin\InstitutionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Institutions" }
        arguments:
            - ~
            - App\ResumeBundle\Entity\Institution
            - ~

    sonata.admin.industry:
        class: App\AdminBundle\Admin\IndustryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Industries" }
        arguments:
            - ~
            - App\ResumeBundle\Entity\Industry
            - ~